---
apiVersion: v2
appVersion: 1.8.0
description: Sharry allows to share files with others in a simple way. It is a self-hosted web application. The basic concept is to upload files and get a url back that can then be shared.
name: sharry
version: 5.4.2
keywords:
  - file sharing
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sharry
icon: https://github.com/eikek/sharry/blob/master/artwork/logo.svg?raw=true
sources:
  - https://github.com/eikek/sharry
  - https://hub.docker.com/r/eikek0/sharry
maintainers:
  - name: auricom
    email: k8s-at-home@xpander.eml.cc
dependencies:
  - name: common
    repository: https://jdhirst.github.io/charts
    version: 4.5.2
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: apache
    version: 9.5.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: apache.enabled
    
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
