apiVersion: v2
name: firefly-iii-stack
version: 0.7.2
description: Installs Firefly III stack (db, app, importer)
type: application
dependencies:
- name: firefly-mariadb
  version: 0.2.2
  condition: firefly-mariadb.enabled
  repository: https://jdhirst.github.io/charts/
- name: redis
  version: 17.7.5
  condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
- name: firefly-iii
  version: 1.3.4
  condition: firefly-iii.enabled
  repository: https://jdhirst.github.io/charts/
- name: importer
  version: 1.3.2
  condition: importer.enabled
  repository: https://jdhirst.github.io/charts/
home: https://github.com/jdhirst/charts
sources:
  - https://github.com/jdhirst/charts
maintainers:
  - name: jdhirst
    email: jdhirst@hirstgroup.net
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
