apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-linkwarden'
  labels:
    katenary.io/component: linkwarden
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 04df533d359dfc5cb24b0bad8d4af2781a5ce98c
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: linkwarden
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
