linkwarden:
  environment:
    DATABASE_URL: postgresql://user:pass@prod-primary.postgres:5432/linkwarden
    EMAIL_FROM: email@example.org
    EMAIL_SERVER: smtp://server:port
    KEYCLOAK_CLIENT_ID: ""
    KEYCLOAK_CLIENT_SECRET: ""
    KEYCLOAK_CUSTOM_NAME: ""
    KEYCLOAK_ISSUER: ""
    NEXT_PUBLIC_CREDENTIALS_ENABLED: ""
    NEXT_PUBLIC_EMAIL_PROVIDER: ""
    NEXT_PUBLIC_KEYCLOAK_ENABLED: ""
    NEXTAUTH_SECRET: ""
    NEXTAUTH_URL: http://localhost:3000/api/v1/auth
    SPACES_BUCKET_NAME: ""
    SPACES_ENDPOINT: ""
    SPACES_KEY: ""
    SPACES_SECRET: secret
  persistence:
    data:
      capacity: 1Gi
      enabled: false
  repository:
    image: ghcr.io/linkwarden/linkwarden
    tag: latest
