apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-discordalert'
  labels:
    katenary.io/component: discordalert
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 664f11b1719d0e593b2c3062ae6ca0d4e3f030a3
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: discordalert
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
