apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-discordalert'
  labels:
    katenary.io/component: discordalert
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 664f11b1719d0e593b2c3062ae6ca0d4e3f030a3
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: discordalert
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: discordalert
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: discordalert
          image: '{{ .Values.discordalert.repository.image }}{{ if ne .Values.discordalert.repository.tag "" }}:{{ .Values.discordalert.repository.tag }}{{ end }}'
          ports:
            - name: discordalert
              containerPort: 9094
          env:
            - name: DISCORD_WEBHOOK
              value: '{{ tpl .Values.discordalert.environment.DISCORD_WEBHOOK . }}'

