apiVersion: v2
name: common
description: Function library for k8s-at-home charts
type: library
version: 4.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - k8s-at-home
  - common
home: https://github.com/jdhirst/charts/tree/master/common
maintainers:
  - name: jdhirst
    email: jdhirst@hirstgroup.net